services:
  db:
    image: postgres:latest
    container_name: imobly-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - imobly-network

volumes:
  postgres_data:

networks:
  imobly-network: